#!/bin/bash

# Print local variables
echo "Local Variables:"
for variable in $(set -o posix ; set)
do
    if [[ "$variable" == local=* ]]; then
        echo "$variable"
    fi
done

# Print environment variables
echo "Environment Variables:"
printenv

# Print functions
echo "Functions:"
declare -F
